### ISSUE TITLE
Device unable to connect

### ISSUE THREAD

**Issue by seahchenhong** [KyleLopin/PSoC-Potentiostat#16]
Hello Kyle, 

I have pull both PSoC-Potentiostat and GUI into my personal computer as of today (26th Feb 2023), and the device is unable to connect. I have placed the EXE file with the folder that has settings.txt and there is not error but device is still unable to connect. 
I would appreciate your help with this :) I am researching this for an electrochemistry project. 

Thanks

Chen Hong
![Screenshot (1)](https://user-images.githubusercontent.com/124116561/221402401-1e1ea73d-087a-4c09-a440-54316c1627dd.png)
![Screenshot (2)](https://user-images.githubusercontent.com/124116561/221402407-70005347-f9fa-4e76-b97d-587fe62086b8.png)
![Screenshot (4)](https://user-images.githubusercontent.com/124116561/221402503-109ef199-8992-4c19-9ed3-1e494d6cb38d.png)

**Comment by KyleLopin** [comment]
Is the release 1.3.0rc?  Do you see any device in the Device manager when you plug it in?

**Comment by seahchenhong** [comment]
Thank you for your reply!

Yes I do see device when I plug in and right now it works and I can do cyclic voltammetry.
However, for Amperometry and ASV, I am unable to do it and the results are as shown in the attached files.

For Amperometry it says serialcomm is not subscriptable 
For ASV is says AmpUSB object is not working
Is the current code supposed to work like this?

Regards,

Chen Hong
![Amp](https://user-images.githubusercontent.com/124116561/224533343-faba38e0-1e32-4f0b-8c78-cc1f674c11a9.jpg)
![ASV](https://user-images.githubusercontent.com/124116561/224533346-def600e7-8524-4360-955c-013e0d1edefe.jpg)

**Comment by KyleLopin** [comment]
Is this fixed now?

**Comment by seahchenhong** [comment]
Yes this is fixed already! I have found a computer that allows port
changes.
