### ISSUE TITLE
PSoC potentiostat for EIS

### ISSUE THREAD

**Issue by ramakrishna722** [KyleLopin/PSoC-Potentiostat#2]
Respected sir,
My aim is to implement psoc potentiostat for Electrochemical impedance spectroscopy.so pls sendband attach the code for EIS.

**Comment by azcaban** [comment]
I'm looking for the same functionality, do you have already implemented it?

**Comment by ramakrishna722** [comment]
RESPECTED SIR,
 I LOADED HEX FILE IN PSOC 5LP CY8CKIT-050 DEVELOPMENT KIT, but it is showing an error...........\
ERROR! --->                                                	| The hex file does not match with the acquired device, please check the device
pls check sir and reply sir.

**Comment by shuvragood** [comment]
s that possible to drive or identify the issue related to DPV-based GUI not opening & Someone identified as well (Azkaban)? Shall we focus on that? Is that 2020 HEX file compatible with the 2020-based GUI? What is the opinion???? Can we increase the number of CV Cycles for the GUI?? Please let me know.

**Comment by shuvragood** [comment]
I am having all code with me (https://drive.google.com/drive/folders/1hKyy2O2HLyh9o4wxKsPFoyXOMyaorkv7)

https://www.duo.uio.no/bitstream/handle/10852/82665/5/Olav-Bjerke---masteroppgave.pdf .

Getting USB Time out error while replicating this into CY8CKIT-059

**Comment by shuvragood** [comment]
> RESPECTED SIR, I LOADED HEX FILE IN PSOC 5LP CY8CKIT-050 DEVELOPMENT KIT, but it is showing an error........... ERROR! ---> | The hex file does not match with the acquired device, please check the device pls check sir and reply sir.
I am having all code with me (https://drive.google.com/drive/folders/1hKyy2O2HLyh9o4wxKsPFoyXOMyaorkv7)

https://www.duo.uio.no/bitstream/handle/10852/82665/5/Olav-Bjerke---masteroppgave.pdf .

Getting USB Time out error while replicating this into CY8CKIT-059.  Check with your device & let me know

**Comment by KyleLopin** [comment]
I added EIS to the roadmap, i do not know when I will get to it
