### ISSUE TITLE
Working!

### ISSUE THREAD

**Issue by ghost** [KyleLopin/PSoC-Potentiostat#4]
Its Working ,Efficiently

**Comment by shuvragood** [comment]
![image - 2022-10-26T143657 377](https://user-images.githubusercontent.com/94778067/197984588-9f0531b7-2cea-42ad-b25b-9294786b9a93.png)
![image - 2022-10-26T143656 052](https://user-images.githubusercontent.com/94778067/197984597-8faa28cd-b42f-4b94-b63d-5dc90031ea6d.png)
![image - 2022-10-26T143654 725](https://user-images.githubusercontent.com/94778067/197984600-ac9aceb8-efdd-4fc3-ad79-6f9e6ac9eac4.png)
![image - 2022-10-26T143653 336](https://user-images.githubusercontent.com/94778067/197984601-dd8c133c-baa2-497c-819c-9eed032fb8be.png)
![image - 2022-10-26T143651 410](https://user-images.githubusercontent.com/94778067/197984607-ffaeaada-055c-47e1-b444-7fd961e88e85.png)
![image - 2022-10-26T143650 303](https://user-images.githubusercontent.com/94778067/197984611-13abbd40-2bf5-405a-a984-ef26607c76f0.png)
![1666749696151](https://user-images.githubusercontent.com/94778067/197984615-b558e219-a507-43f5-910d-3e73230ddce0.jpg)
![WhatsApp Image 2022-10-26 at 13 47 52](https://user-images.githubusercontent.com/94778067/197984624-88d99b69-7827-43ef-805a-b1ecdeb0e6cf.jpeg)
[Potentiostat_GUI-master (17).zip](https://github.com/KyleLopin/PSoC-Potentiostat/files/9867910/Potentiostat_GUI-master.17.zip)
[PSoC-Potentiostat-master (6).zip](https://github.com/KyleLopin/PSoC-Potentiostat/files/9867911/PSoC-Potentiostat-master.6.zip)
