### ISSUE TITLE
Anything substitute chip to use as PSoC for ASV?

### ISSUE THREAD

**Issue by skyds4499** [KyleLopin/PSoC-Potentiostat#7]
Hi!
I just find the paper you wrote.
I really happy to use it for my research, analysis or heavy metal in water .
But also, I found PSoC 5LP kits are very expensive for discontinued.
Is there anything recommend for substitute of  PSoC 5LP?

**Comment by shuvragood** [comment]
I am having all code with me (https://drive.google.com/drive/folders/1hKyy2O2HLyh9o4wxKsPFoyXOMyaorkv7)

https://www.duo.uio.no/bitstream/handle/10852/82665/5/Olav-Bjerke---masteroppgave.pdf .


Getting USB Time out error while replicating this into CY8CKIT-059

**Comment by skyds4499** [comment]
> I am having all code with me (https://drive.google.com/drive/folders/1hKyy2O2HLyh9o4wxKsPFoyXOMyaorkv7)
> 
> https://www.duo.uio.no/bitstream/handle/10852/82665/5/Olav-Bjerke---masteroppgave.pdf .
> 
> Getting USB Time out error while replicating this into CY8CKIT-059

thank you, I'll check that

**Comment by shuvragood** [comment]
> > I am having all code with me (https://drive.google.com/drive/folders/1hKyy2O2HLyh9o4wxKsPFoyXOMyaorkv7)
> > https://www.duo.uio.no/bitstream/handle/10852/82665/5/Olav-Bjerke---masteroppgave.pdf .
> > Getting USB Time out error while replicating this into CY8CKIT-059
> 
> thank you, I'll check that
Please do check & let me update .....Can
it be implemented in by different way to retrieve data with the same logic ?Means sending command to device & get the data

**Comment by skyds4499** [comment]
> > > I am having all code with me (https://drive.google.com/drive/folders/1hKyy2O2HLyh9o4wxKsPFoyXOMyaorkv7)
> > > https://www.duo.uio.no/bitstream/handle/10852/82665/5/Olav-Bjerke---masteroppgave.pdf .
> > > Getting USB Time out error while replicating this into CY8CKIT-059
> > 
> > 
> > thank you, I'll check that
> > Please do check & let me update .....Can
> > it be implemented in by different way to retrieve data with the same logic ?Means sending command to device & get the data

Well, I'll gonna use FreeSoC2 Development Board - PSoC5LP.
It is hard to buy proper board at proper price in proper time for now.

BTW, how did you got the carbon electrode? 
I sent mail to Mr. Hassan (correspond author of  that electrode). But, mail weren't sent to him properly.
Is there any other way to contact him?

**Comment by shuvragood** [comment]
I don't know Can you replicate this project for me?

**Comment by shuvragood** [comment]
Have you replicated that project I have shared? Kindly guide me about your code

**Comment by skyds4499** [comment]
> 

Well, I'm trying to replicate the original project(One from KyleLopin). But, have to wait for board and other materials. So, nothing confirmed yet for now.
Also, I'm looking for some electrodes for measurement. The rod type electrodes are quite expensive(conventional ones). For buying three of them, cost more then 1000 dollars roughly. That's why I looking for Screen printed electrode. Easy to use outside and inside.

**Comment by KyleLopin** [comment]
Cypress has confirmed that the CY8CKIT-059 are being produced now, but will take awhile to restock them.  I am looking at trying to reproduce the code with a TI MCU, but that will take awhile and I'm still not sure it will work.

For the carbon electrode you can use mechanical pencil graphite, the different types give slightly different results.
